### ISSUE TITLE
Gages reference locations.

### ISSUE THREAD

**Issue by dblodgett-usgs** [dblodgett-usgs/geoconnex_prep#1]
We will use this issue to plan implementation of an initial gages reference layer. Placeholder for now. Please contribute sources of gage network locations in the comments and we'll work this description into a good summary of what needs to be brought together.

Long run, this will include gage-locations that are non-NWIS. Initial work will include NWIS only.

Data Sources:
1. All of the NWISWeb site file as a base. [Done here.](https://github.com/dblodgett-usgs/geoconnex_prep/blob/master/R/get_data.R#L1)
1. GageLoc [published here](https://www.sciencebase.gov/catalog/item/577445bee4b07657d1a991b6).
1. GagesIII Unpublished -- request to make available as pre-release has been made.
1. Additional locations?

For those not addressed in the above sources, we will follow an indexing method that snaps and prioritizes attributes like drainage area, waterbody/stream name, etc. Will work with HydroLink and  /or other tools being used for bridges and dams in other geoconnex reference locations.

@mikejohnson51 @dwief-usgs -- going to need your help.

**Comment by ksonda** [comment]
Is this USGS/Fed assets only or do you want state/ utility stuff too?

**Comment by dblodgett-usgs** [comment]
Long run, I see this being all. Initially, maybe just fed, but I'm open to whatever is easy to get in an initial set.

**Comment by ksonda** [comment]
[California Data Exchange Center](https://cdec.water.ca.gov/cdecstations) (can filter to flow/stage sensors and download excel table with lat/lon) 662 river stage stations, 216 of which are USGS, 20 USBR, 40 USACE, 225 CA DWR, and the rest ~160 are various local governments and utilities

[Colorado Current Surface Water Conditions](https://data.colorado.gov/Water/Current-Surface-Water-Conditions-in-Colorado/4yw9-a5y6/data) 1167 stream and diversion discharge stations (need to filter out reservoir storage monitor stations). 622 CDWR, 319 USGS, 2 NPS, 24 USBR, remainder local government or conservation distrcts

[Iowa Flood Information System](http://ifis.iowafloodcenter.org/ifis/ws/) 182 gages, mostly mounted on bridges.

[TX DOT Bridge gages](https://utexas.app.box.com/s/cfxzzc4aqnh4cwjkqffdba4zh26k66q7)

[Nebraska DENR Gage/Canal/Reservoir Gages](https://nednr.nebraska.gov/RealTime/Stations/StationsList)

Working on a New Mexico inventory that definitly exists for water rights allocations

**Comment by ksonda** [comment]
New Mexico Office of State Engineer collection of non-USGS gages used for water rights admin

[OSE_Gauges.zip](https://github.com/dblodgett-usgs/geoconnex_prep/files/4600641/OSE_Gauges.zip)

**Comment by ksonda** [comment]
is there a reason this isn't over on internetofwater/geoconnex.us?

**Comment by dblodgett-usgs** [comment]
Yeah, it's for implementation in this repository -- I'll be adding a sibling issue over there soon.
